StatsBundle\Entity\MpgLeague:
    type: entity
    table: null
    repositoryClass: StatsBundle\Repository\MpgLeagueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
#    manyToOne:
#        real_league:
#            targetEntity: RealLeague
#            inversedBy: mpg_leagues
#            joinColumn:
#                name: real_league_id
#                referencedColumnName: id
#    oneToMany:
#        mpg_teams:
#            targetEntity: MpgTeam
#            mappedBy: mpg_league
#        mpg_matches:
#            targetEntity: MpgMatch
#            mappedBy: mpg_match
    fields:
        name:
            type: string
            length: 255
        country:
            type: string
            length: 255
        teamAmount:
            type: smallint
            column: team_amount
        upcomingWeek:
            type: smallint
            nullable: true
            column: upcoming_week
        weekStart:
            type: smallint
            column: week_start
        weekEnd:
            type: smallint
            column: week_end
        realLeagueId:
            type: integer
            column: real_league_id
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
        hash:
            type: string
            length: 255
    lifecycleCallbacks: {  }
