StatsBundle\Entity\MpgPlayerMatch:
    type: entity
    table: null
    repositoryClass: StatsBundle\Repository\MpgPlayerMatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        goalsScored:
            type: smallint
            column: goals_scored
        ownGoalsScored:
            type: smallint
            column: own_goals_scored
        bonus:
            type: float
    lifecycleCallbacks: {  }
