StatsBundle\Entity\MpgTeam:
    type: entity
    table: null
    repositoryClass: StatsBundle\Repository\MpgTeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        mpg_league:
            targetEntity: MpgLeague
            inversedBy: mpg_teams
            joinColumn:
                name: mpg_league_id
                referencedColumnName: id
    oneToMany:
        mpg_matches:
            targetEntity: MpgMatch
            mappedBy: mpg_team
    fields:
        name:
            type: string
            length: 255
        mpgLeagueId:
            type: integer
            column: mpg_league_id
        mpgUserId:
            type: integer
            column: mpg_user_id
        owner:
            type: string
            length: 255
        stadium:
            type: string
            length: 255
        rank:
            type: smallint
        realLeagueId:
            type: smallint
            column: real_league_id
        seasonGoalsTaken:
            type: smallint
            column: season_goals_taken
        seasonGoalsTakenHome:
            type: smallint
            column: season_goals_taken_home
        seasonGoalsAway:
            type: smallint
            column: season_goals_away
        seasonGoalsScored:
            type: smallint
            column: season_goals_scored
        seasonGoalsScoredHome:
            type: smallint
            column: season_goals_scored_home
        seasonGoalsScoredAway:
            type: smallint
            column: season_goals_scored_away
        seasonVictories:
            type: smallint
            column: season_victories
        seasonVictoriesHome:
            type: smallint
            column: season_victories_home
        seasonVictoriesAway:
            type: smallint
            column: season_victories_away
        seasonDefeats:
            type: smallint
            column: season_defeats
        seasonDefeatsHome:
            type: smallint
            column: season_defeats_home
        seasonDefeatsAway:
            type: smallint
            column: season_defeats_away
        seasonDraws:
            type: smallint
            column: season_draws
        seasonDrawsHome:
            type: smallint
            column: season_draws_home
        seasonDrawsAway:
            type: smallint
            column: season_draws_away
    lifecycleCallbacks: {  }
