StatsBundle\Entity\RealMatch:
    type: entity
    table: null
    repositoryClass: StatsBundle\Repository\RealMatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        home_team:
            targetEntity: RealTeam
            inversedBy: home_matches
            joinColumn:
                onDelete: CASCADE
                name: home_team_id
                referencedColumnName: id
        real_league:
            targetEntity: RealLeague
            inversedBy: real_matches
            joinColumn:
                onDelete: CASCADE
                name: real_league_id
                referencedColumnName: id
        away_team:
            targetEntity: RealTeam
            inversedBy: away_matches
            joinColumn:
                onDelete: CASCADE
                name: away_team_id
                referencedColumnName: id
    oneToMany:
        player_real_matches:
            targetEntity: PlayerRealMatch
            mappedBy: real_match
    fields:
        realLeagueId:
            type: integer
            column: real_league_id
        dataHash:
            column: data_hash
            type: string
            length: 255
        mpgId:
            type: integer
            column: mpg_id
            unique: true
        season:
            type: integer
            column: season
        homeTeamId:
            type: integer
            column: home_team_id
        awayTeamId:
            type: integer
            column: away_team_id
        homeTeamRank:
            type: smallint
            column: home_team_rank
            nullable: true
        awayTeamRank:
            type: smallint
            column: away_team_rank
            nullable: true
        homeTeamScore:
            type: smallint
            column: home_team_score
        awayTeamScore:
            type: smallint
            column: away_team_score
        played:
            type: boolean
            column: played
            options:
                default: 0
        week:
            type: smallint
        date:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
