StatsBundle\Entity\RealLeague:
    type: entity
    table: null
    repositoryClass: StatsBundle\Repository\RealLeagueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        real_teams:
            targetEntity: RealTeam
            mappedBy: real_league
        real_matches:
            targetEntity: RealMatch
            mappedBy: real_league
        players:
            targetEntity: Player
            mappedBy: real_league
    fields:
        name:
            type: string
            length: 255
        country:
            type: string
            length: 255
            nullable: true
        teamAmount:
            type: smallint
            column: team_amount
        mpgId:
            type: integer
            column: mpg_id
            unique: true
        upcomingWeek:
            type: smallint
            column: upcoming_week
        season:
            type: integer
    lifecycleCallbacks: {  }
