push_match_details:
    path:     /pushMatchDetails
    methods: [ post ]
    defaults: { _controller: StatsBundle:Ajax:pushMatchDetails }

push_week_summary:
    path:     /pushWeekSummary
    methods: [ post ]
    defaults: { _controller: StatsBundle:Ajax:pushWeekSummary }

push_player_quotations:
    path:     /pushPlayerQuotations
    methods: [ post ]
    defaults: { _controller: StatsBundle:Ajax:pushPlayerQuotations }

