# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    stats.aggregator:
        class: StatsBundle\Service\Aggregator
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    stats.player_manager:
        class: StatsBundle\Service\PlayerManager
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    stats.real_team_manager:
        class: StatsBundle\Service\RealTeamManager
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    stats.synonym_manager:
        class: StatsBundle\Service\SynonymManager
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
