<?php

namespace StatsBundle\Repository;

/**
 * MpgLeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpgLeagueRepository extends \Doctrine\ORM\EntityRepository
{
}
