<?php

namespace StatsBundle\Repository;

/**
 * MpgMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpgMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
