<?php

namespace StatsBundle\Repository;

/**
 * MpgPlayerMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpgPlayerMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
