<?php

namespace StatsBundle\Repository;

/**
 * MpgTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpgTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
