<?php

namespace StatsBundle\Repository;

/**
 * RealPlayerMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealPlayerMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
