<?php

namespace StatsBundle\Repository;

/**
 * PlayerRealMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRealMatchRepository extends \Doctrine\ORM\EntityRepository
{
    public function aggregateMatchData($leagueId){
        /**
        SELECT player_id as id,
            real_match.season as season,
            lastname,
            SUM(has_started) as tit,
            SUM(has_entered) as rempl,
            SUM(yellow_cards) as yc,
            SUM(red_card) as rc,
            SUM(goals) AS gf,
            SUM(assists) as assists,
            SUM(own_goals) as ga,
            AVG(rating),
            SUM(errors_leading_to_goal) as fuckups
        FROM player_real_match
        INNER JOIN player
            ON player.id = player_real_match.player_id
        INNER JOIN real_match
            ON real_match.id = player_real_match.real_match_id
        WHERE player.real_league_id = 1
        GROUP BY player_id, season
        ORDER BY season DESC;
         */
    }
}
