<?php

namespace StatsBundle\Repository;

/**
 * RealTeamRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealTeamRankRepository extends \Doctrine\ORM\EntityRepository
{
}
