<?php

namespace StatsBundle\Repository;

/**
 * RealMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealMatchRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWeekGames($leagueId = 1, $week = 1)
    {

        $query = $this->createQueryBuilder('rm')
            ->where('rm.real_league_id = :real_league_id')
            ->setParameter('real_league_id', $leagueId)
            ->andWhere('rm.real_league_id = :real_league_id')
            ->setParameter('week', $week)
            ->getQuery();

        $games = $query->getResult();

        return $games;
    }
}
