<?php

namespace StatsBundle\Repository;

/**
 * RealLeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealLeagueRepository extends \Doctrine\ORM\EntityRepository
{
    
}
