<?php

namespace StatsBundle\Repository;

/**
 * RealTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealTeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTeamByName($name, $currentWeek = false)
    {
        $query = $this->createQueryBuilder()
            ->select('rt', 'rtr')
            ->where('rt.name = :team_name')
            ->setParameter('team_name', $name)
            ->getQuery();

        $games = $query->getResult();

        return $games;
    }
}
