<?php

namespace StatsBundle\Repository;

/**
 * SynonymRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SynonymRepository extends \Doctrine\ORM\EntityRepository
{
}
