player_index:
    path:     /
    defaults: { _controller: "StatsBundle:Player:index" }
    methods:  GET

player_show:
    path:     /{id}/show
    defaults: { _controller: "StatsBundle:Player:show" }
    methods:  GET
